- uses: actions/checkout@v4
      # هذه الخطوة مهمة لتثبيت بيئة Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # يمكنك تغييرها إلى 'beta' أو 'dev' حسب إصدار Flutter اللي تستخدمه
      # بعد ما يتم إعداد Flutter، نقوم بتنزيل حزم المشروع
      - run: flutter pub get
      # ثم نبني تطبيق الويب لوضع النشر (release)
      - run: flutter build web --release 
      # وأخيراً، نقوم بالنشر إلى Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MED_AD }}
          channelId: live
          projectId: med-ad
